---
# tasks file for fx.api.frontend
    - name: Configure nginx
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify:
      - restart nginx

    - name: Configure nginx default vhost
      copy:
        src: conf.d/default.conf
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
      notify:
      - restart nginx

    - name: Configure nginx api.fxhistoricaldata.com vhost
      copy:
        src: conf.d/api.conf
        dest: /etc/nginx/conf.d/api.conf
        owner: root
        group: root
        mode: 0644
      notify:
      - restart nginx
