---
# tasks file for fx.api.frontend
- name: Configure nginx
  template:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  with_items:
    - conf.d/api.conf

- name: Create letsencrypt acme-challenge directory
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ api.acme_base_dir }}{{ fx.certbot_challenge_dir }}"
