---
# tasks file for fx.sniper

- name: Download {{role_path|basename}} docker images
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - fxtrader/finance-hostedtrader
#    - redis
