---
# tasks file for fx.sniper
- name: "Download {{role_path|basename}} docker image"
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - fxtrader/snipers-client
#    - redis

- name: snipers client
  docker_container:
    name: snipers-client
    image: fxtrader/snipers-client
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader:ro"
    links:
      - smtp:smtp
      - snipers-api:snipers-api
    restart_policy: always
    state: started
