---
# tasks file for fx.sniper
- name: "Download {{role_path|basename}} docker image"
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - fxtrader/snipers-client
#    - redis

- name: snipers client
  docker_container:
    name: snipers-client
    image: fxtrader/snipers-client
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader:ro"
    networks:
      - name: "{{ fx.docker.network.name }}"
    purge_networks: yes
    restart_policy: always
    state: started
    env:
      SNIPER_JWT_TOKEN: "{{ sniper_client.JWT_TOKEN }}"
      SNIPER_ENDPOINT: "{{ 'https' if snipers.ssl else 'http'}}://{{  snipers.hostname }}"
