---
# tasks file for fx.base
- name: Create fxtrader.cfg directory
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{fx['cfgdir']}}"
    - "{{fx['datadir']}}"

- name: Setup fx.yml config file
  template:
    src: fx.yml.j2
    dest: "{{ fx['cfgdir'] }}/fx.yml"
    owner: root
    group: root
    mode: 0644

- name: Setup fxtrader.log.conf file
  copy:
    src: fxtrader.log.conf
    dest: "{{ fx['cfgdir'] }}/fxtrader.log.conf"
    owner: root
    group: root
    mode: 0644
