---
# tasks file for fx.base
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - bash-completion
    - bind-utils
    - net-tools
    - tmux
    - strace

- name: Create fx directories
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{fx['cfgdir']}}"
    - "{{fx['datadir']}}"

- name: Setup fx.yml config file
  template:
    src: fx.yml.j2
    dest: "{{ fx['cfgdir'] }}/fx.yml"
    owner: root
    group: root
    mode: 0644

- name: Setup fxtrader.log.conf file
  copy:
    src: fxtrader.log.conf
    dest: "{{ fx['cfgdir'] }}/fxtrader.log.conf"
    owner: root
    group: root
    mode: 0644

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: fx network
  docker_network:
    name: "{{ fx.docker.network.name }}"
    driver: bridge
  
