---
# tasks file for fx.datafeed

- name: Create datafeed mariadb cfg directory
  file:
    path:  "{{ datafeed['cfgdir'] }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Setup datafeed mariadb config files
  copy:
    src: "mariadb/{{ item }}"
    dest: "{{ datafeed['cfgdir'] }}/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mysqld_safe_syslog.cnf
    - fxtrader.cnf

- name: Download {{role_path|basename}} docker images
  docker_image:
    name: "{{ item }}"
  with_items:
    - fxtrader/finance-hostedtrader
    - mysqludf/ta

- name: fxdata container
  docker_container:
    name: fxdata
    image: mysqludf/ta
    volumes:
      - "{{datafeed['datadir']}}:/var/lib/mysql"
      - "{{datafeed['cfgdir']}}:/etc/mysql/conf.d"
      - "{{fx['srcdir']}}:/root/src"
    hostname: data
    state: started
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "{{ fx['datafeed']['dbname'] }}"
      MYSQL_USER: "{{ fx['datafeed']['dbuser'] }}"
      MYSQL_PASSWORD: "{{ fx['datafeed']['dbpass'] }}"

- name: fxdata schema
  docker_container:
    name: fxdataschema
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader"
    links:
      - fxdata:fxdata
    command: "/bin/bash -c 'fx-create-db-schema.pl | fx-db-client.pl'"
    state: started

- name: fxfeed container
  docker_container:
    name: fxcmfeed
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader"
    links:
      - fxdata:fxdata
    command: "fx-download-fxcm.pl --verbose --timeframes=300 --numItems=15"
    state: present

- name: fxcm data download cronjob
  copy:
    src: cron.d/fxcm_download_data
    dest: /etc/cron.d/fxcm_download_data
    owner: root
    group: root
    mode: 0644
