---
# tasks file for fx.datafeed

- name: Create datafeed mariadb directories
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ datafeed['cfgdir'] }}"
    - "{{ datafeed['datadir'] }}"

- name: Setup datafeed mariadb config files
  copy:
    src: "mariadb/{{ item }}"
    dest: "{{ datafeed['cfgdir'] }}/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mysqld_safe_syslog.cnf
    - fxtrader.cnf

- name: Download {{role_path|basename}} mysqludf/ta
  docker_image:
    name: mysqludf/ta
    source: pull

- name: fxdatafeed container
  docker_container:
    name: fxdatafeed
    image: mysqludf/ta
    volumes:
      - "{{datafeed['datadir']}}:/var/lib/mysql"
      - "{{datafeed['cfgdir']}}:/etc/mysql/conf.d"
      - "{{fx['srcdir']}}:/root/src"
    hostname: data
    state: started
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "{{ datafeed['db']['name'] }}"
      MYSQL_USER: "{{ datafeed['db']['user'] }}"
      MYSQL_PASSWORD: "{{ datafeed['db']['pass'] }}"

- name: Download {{role_path|basename}} fxtrader/finance-hostedtrader
  docker_image:
    name: fxtrader/finance-hostedtrader
    source: pull

- name: fxdatafeed schema
  docker_container:
    name: fxdatafeedschema
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader"
    links:
      - fxdatafeed:fxdatafeed
    command: "/bin/bash -c 'fx-create-db-schema.pl | fx-db-client.pl'"
    state: started

- name: fxcm data download cronjob
  copy:
    src: cron.d/fxcm_download_data
    dest: /etc/cron.d/fxcm_download_data
    owner: root
    group: root
    mode: 0644

- name: fxfeed oanda container
  docker_container:
    name: oandafeed
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader"
    links:
      - fxdatafeed:fxdatafeed
    command: "fx-download.pl --verbose --timeframes=60 --numItems=15 --provider=oanda"
    state: present

- name: fxfeed oanda historical container
  docker_container:
    name: oandahistorical
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader"
    links:
      - fxdatafeed:fxdatafeed
    command: "fx-download.pl --verbose --timeframes=60 --numItems=1440 --provider=oanda_historical"
    state: present

- name: fxfeed oanda cleanup container
  docker_container:
    name: oandacleanup
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader"
    links:
      - fxdatafeed:fxdatafeed
    command: "fx-cleanup-db.pl --provider=oanda"
    state: present

- name: oanda data download cronjob
  copy:
    src: cron.d/oanda_download_data
    dest: /etc/cron.d/oanda_download_data
    owner: root
    group: root
    mode: 0644
