---
# tasks file for fx.datafeed

- name: Download {{role_path|basename}} docker images
  docker_image:
    name: "{{ item }}"
  with_items:
    - fxtrader/finance-hostedtrader
    - mysqludf/ta

- name: fxdata container
  docker_container:
    name: fxdata
    image: mysqludf/ta
    volumes:
      - /root/mysql:/var/lib/mysql
      - /root/fxtrader.cfg/mariadb:/etc/mysql/conf.d
      - /root/src:/root/src
    hostname: data
    state: started
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "{{ fx['datafeed']['dbname'] }}"
      MYSQL_USER: "{{ fx['datafeed']['dbuser'] }}"
      MYSQL_PASSWORD: "{{ fx['datafeed']['dbpass'] }}"

- name: fxfeed container
  docker_container:
    name: fxcmfeed
    image: fxtrader/finance-hostedtrader
    volumes:
      - /root/fxtrader.cfg:/etc/fxtrader
    links:
      - fxdata:fxdata
    command: "fx-download-fxcm.pl --verbose --timeframes=300 --numItems=15"
    state: present

- name: fxcm data download cronjob
  copy:
    src: cron.d/fxcm_download_data
    dest: /etc/cron.d/fxcm_download_data
    owner: root
    group: root
    mode: 0644
