---
# tasks file for fx.datafeed

- name: Create datafeed mariadb directories
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ datafeed['cfgdir'] }}"
    - "{{ datafeed['datadir'] }}"

- name: Setup datafeed mariadb config files
  copy:
    src: "mariadb/{{ item }}"
    dest: "{{ datafeed['cfgdir'] }}/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mysqld_safe_syslog.cnf
    - fxtrader.cnf

- name: "Download {{role_path|basename}} fxtrader/ta"
  docker_image:
    name: fxtrader/ta
    source: pull

- name: fxdatafeed container
  docker_container:
    name: fxdatafeed
    image: fxtrader/ta
    volumes:
      - "{{datafeed['datadir']}}:/var/lib/mysql"
      - "{{datafeed['cfgdir']}}:/etc/mysql/conf.d:ro"
    hostname: data
    state: started
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "{{ datafeed['db']['name'] }}"
      MYSQL_USER: "{{ datafeed['db']['user'] }}"
      MYSQL_PASSWORD: "{{ datafeed['db']['pass'] }}"

- name: Download {{role_path|basename}} fxtrader/finance-hostedtrader
  docker_image:
    name: fxtrader/finance-hostedtrader
    source: pull

- name: fxdatafeed schema
  docker_container:
    name: fxdatafeedschema
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader:ro"
    links:
      - fxdatafeed:fxdatafeed
    command: "/bin/bash -c 'fx-create-db-schema.pl | fx-db-client.pl'"
    state: started

- name: fxcm data download cronjob
  copy:
    src: cron.d/fxcm_download_data
    dest: /etc/cron.d/fxcm_download_data
    owner: root
    group: root
    mode: 0644

- name: fxfeed oanda container
  docker_container:
    name: oandafeed
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader:ro"
    links:
      - fxdatafeed:fxdatafeed
    command: "fx-download.pl --verbose --timeframes=60 --numItems=15 --provider=oanda"
    state: present

- name: fxfeed oanda historical container
  docker_container:
    name: oandahistorical
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader:ro"
    links:
      - fxdatafeed:fxdatafeed
    command: "fx-download.pl --verbose --timeframes=60 --numItems=2880 --provider=oanda_historical"
    state: present

- name: fxfeed oanda cleanup container
  docker_container:
    name: oandacleanup
    image: fxtrader/finance-hostedtrader
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader:ro"
    links:
      - fxdatafeed:fxdatafeed
    command: "fx-cleanup-db.pl --provider=oanda"
    state: present

- name: oanda data download cronjob
  copy:
    src: cron.d/oanda_download_data
    dest: /etc/cron.d/oanda_download_data
    owner: root
    group: root
    mode: 0644

- name: Set useful shell aliases
  lineinfile:
    dest: /etc/profile.d/fxtrader.sh
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: root
    state: present
    insertafter: EOF
    create: true
  loop:
    - { regexp: "alias fx-shell=",  line: "alias fx-shell='touch $HOME/fx-shell.bash_history;docker run -ti --env http_proxy --env https_proxy --rm --link fxdatafeed:fxdatafeed --link smtp:smtp -v $HOME/fx/cfg:/etc/fxtrader -v $HOME/fx-shell.bash_history:/root/.bash_history -v ~/src:/src -h fx-shell fxtrader/finance-hostedtrader bash'"}
    - { regexp: "alias fx-db=",  line: "alias fx-db='docker run -it --rm --link fxdatafeed:mysql mariadb sh -c '\\''exec mysql -A -h\"$MYSQL_PORT_3306_TCP_ADDR\" -P\"$MYSQL_PORT_3306_TCP_PORT\" -u{{datafeed['db']['user']}} -p{{datafeed['db']['pass']}} {{datafeed['db']['name']}}'\\'''"}
    - { regexp: "alias fx-db-root=",  line: "alias fx-db-root='docker run -it --rm --link fxdatafeed:mysql mariadb sh -c '\\''exec mysql -A -h\"$MYSQL_PORT_3306_TCP_ADDR\" -P\"$MYSQL_PORT_3306_TCP_PORT\" -uroot -p\"$MYSQL_ROOT_PASSWORD\" {{datafeed['db']['name']}}'\\'''"}
