---
- name: Download portainer docker image
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - portainer/portainer-ce

- name: Create portainer data directory for persistent storage
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ portainer['datadir'] }}"

- name: Setup portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    volumes:
      - "{{portainer['datadir']}}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    published_ports:
      - 127.0.0.1:9000:9000
    restart_policy: always
    state: started

- name: Configure nginx to proxy to the portainer container
  template:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  with_items:
    - conf.d/portainer.conf

- name: Create letsencrypt acme-challenge directory
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ portainer.acme_base_dir }}{{ fx.certbot_challenge_dir }}"
