---
- name: Download portainer docker image
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - portainer/portainer

- name: Setup portainer container
  docker_container:
    name: portainer
    image: portainer/portainer
    volumes:
      - "{{fx['datadir']}}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    published_ports:
      - 9000:9000
    restart_policy: always
    state: started

- name: Configure nginx to proxy to the portainer container
  template:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  with_items:
    - conf.d/portainer.conf
