---
- name: "Download {{role_path|basename}} docker image"
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - fxtrader/snipers-api

- name: snipers-api container
  docker_container:
    name: snipers-api
    image: fxtrader/snipers-api
    networks:
      - name: "{{ fx.docker.network.name }}"
    purge_networks: yes
    volumes:
      - "{{fx['cfgdir']}}:/etc/fxtrader:ro"
    published_ports:
      - 127.0.0.1:5567:4567
    restart_policy: always
    state: started
    env:
      FX-SNIPERS-ALLOW-ORIGIN: "{{ snipers['allow_origin'] }}"
    command: "ruby /webapp/app.rb -o 0.0.0.0"

- name: Configure nginx
  template:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  with_items:
    - conf.d/snipers.conf

- name: Create letsencrypt acme-challenge directory
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ snipers.acme_base_dir }}{{ fx.certbot_challenge_dir }}"

- name: Set useful shell aliases
  template:
    src: "etc/profile.d/{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - fx.snipers.backend.sh
