---

- name: "Download {{role_path|basename}} docker images"
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - fxtrader/web

- name: nginx container
  docker_container:
    name: fx-ui
    image: fxtrader/web
    published_ports:
      - 127.0.0.1:8080:80
    restart_policy: always
    state: started
    volumes: "{{ ui.fx_web.volumes }}"

- name: Configure nginx
  template:
    src: "nginx/{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  with_items:
    - conf.d/ui.conf

- name: Create letsencrypt acme-challenge directory
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ ui.acme_base_dir }}{{ fx.certbot_challenge_dir }}"
