---
- name: Download Docker Event Monitor docker image
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - quaide/dem

- name: Create Docker Event Monitor config directory
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ dem['cfgdir'] }}"

- name: Configure Docker Event Monitor
  template:
    src: "dem.conf.yml"
    dest: "{{dem['cfgdir']}}/dem.conf.yml"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart dem

- name: Setup Docker Event Monitor container
  docker_container:
    name: dem
    image: quaide/dem
    volumes:
      - "{{dem['cfgdir']}}/dem.conf.yml:/app/conf.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart_policy: always
    state: started
