---
# tasks file for fx.dataaccounts

- name: Create dataaccounts mariadb cfg directory
  file:
    path:  "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
      - "{{ dataaccounts['cfgdir'] }}"
      - "{{ dataaccounts['datadir'] }}"
      - "{{ dataaccounts['initdir'] }}"

- name: Setup dataaccounts mariadb config files
  copy:
    src: "{{ item }}"
    dest: "{{ dataaccounts['cfgdir'] }}/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mysqld_safe_syslog.cnf

- name: Setup dataaccounts mariadb init files
  copy:
    src: "{{ item }}"
    dest: "{{ dataaccounts['initdir'] }}/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 0000-baseschema.sql

- name: Download {{role_path|basename}} mysqludf/ta
  docker_image:
    name: mysqludf/ta

- name: fxdataaccounts container
  docker_container:
    name: fxdataaccounts
    image: mysqludf/ta
    volumes:
      - "{{dataaccounts['datadir']}}:/var/lib/mysql"
      - "{{dataaccounts['cfgdir']}}:/etc/mysql/conf.d"
      - "{{dataaccounts['initdir']}}:/docker-entrypoint-initdb.d"
    state: started
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "{{ dataaccounts['db']['name'] }}"
      MYSQL_USER: "{{ dataaccounts['db']['user'] }}"
      MYSQL_PASSWORD: "{{ dataaccounts['db']['pass'] }}"
