---

- name: Setup dev env
  hosts: localhost

  vars:
    fx:
      cfgdir: /root/fx/cfg
    dotfiles_repo: "git@github.com:joaocosta/home.git"
    dotfiles_repo_local_destination: "~/src/home"
    dotfiles_files:
      - .vimrc
      - .gitconfig
      - .tmux.conf

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "git@github.com:{{item}}.git"
        dest: "{{ ansible_env.HOME }}/src/fx/{{ item.split('/')[1] }}"
      loop:
        - fx-trader/architecture
        - fx-trader/Finance-API-Data
        - fx-trader/Finance-HostedTrader
        - fx-trader/Finance-snipers
        - fx-trader/fxhistoricaldata_website_static
        - fx-trader/snipers-api
        - fx-trader/fx-web
        - fx-trader/fx-ansible
        - mysqludf/lib_mysqludf_ta

  roles:
    - { role: geerlingguy.dotfiles }
