---

- name: Setup dev env
  hosts: localhost

  vars:
    fx:
      cfgdir: /root/fx/cfg
    dotfiles_repo: "git@github.com:joaocosta/home.git"
    dotfiles_repo_local_destination: "~/src/home"
    dotfiles_files:
      - .vimrc
      - .gitconfig
      - .tmux.conf

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "git@github.com:{{item}}.git"
        dest: "{{ ansible_env.HOME }}/src/fx/{{ item.split('/')[1] }}"
      loop:
        - fx-trader/Finance-API-Data
        - fx-trader/Finance-HostedTrader
        - fx-trader/Finance-snipers
        - fx-trader/fxhistoricaldata_website_static
        - fx-trader/snipers-api
        - fx-trader/fx-web
        - fx-trader/fx-ansible
        - mysqludf/lib_mysqludf_ta

    - name: Install dev packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - make

    - name: Set useful shell aliases
      lineinfile:
        dest: /etc/profile.d/fx-dev.sh
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        owner: root
        state: present
        insertafter: EOF
        create: true
      loop:
        - { regexp: "alias docker-build=",  line: "alias docker-build='docker build -t $(cat .dockertag):latest .'"}
        - { regexp: "alias docker-push=",  line: "alias docker-push='docker push $(cat .dockertag)'"}
        - { regexp: "export PATH=",  line: "export PATH=$PATH:~/src/home/bin"}

  roles:
    - { role: geerlingguy.dotfiles }
