---

- name: Setup fx server
  hosts: all

  roles:
    - { role: fx.api.frontend, tags: [ fx, api, snipers ] }
    - { role: fx.datafeed, tags: [ fx, datafeed ]  }
    - { role: fx.api.backend, tags: [ fx, api ]  }
    - { role: fx.sniper, tags: [ fx ]  }
    - { role: fx.snipers-db, tags: [ fx, snipers ]  }
    - { role: fx.snipers.backend, tags: [ fx, snipers ]  }
    - { role: fx.portainer, tags: [ fx, monitor ]  }

  tasks:
    - name: Make sure we have a wheel group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

#    - name: Download redis docker images
#      docker_image:
#        name: "{{ item }}"
#      with_items:
#        - redis

#    - name: signal-scan-redis container
#      docker_container:
#        name: signal-scan-redis
#        image: redis
#        volumes:
#          - "{{fx['datadir']}}/signal-scan-redis:/data"
#        state: started
#        command: "redis-server --appendonly yes"
