---

- name: Setup fx server
  hosts: all

# The latest ansible 2.12 uses python 3.8 but one of the dependencies (python3-firewall) is only available in python 3.6
# to workaround it, i'm setting ansible_python_interpreter to use the same python that python3-firewall uses
# See https://stackoverflow.com/questions/67193176/python-module-firewall-not-found/72448139#72448139 and https://bugzilla.redhat.com/show_bug.cgi?id=2091931.
  vars:
      - ansible_python_interpreter: /usr/bin/python3

  roles:
    - { role: fx.api.frontend, tags: [ fx, api, snipers ] }
    - { role: fx.datafeed, tags: [ fx, datafeed ]  }
    - { role: fx.api.backend, tags: [ fx, api ]  }
    - { role: fx.snipers-db, tags: [ fx, snipers ]  }
    - { role: fx.snipers.backend, tags: [ fx, snipers ]  }
    - { role: fx.sniper, tags: [ fx, snipers ]  }
    - { role: fx.ui, tags: [ fx, ui ]  }
    - { role: fx.portainer, tags: [ fx, monitor, portainer ]  }
    - { role: fx.dem, tags: [ fx, monitor, dem ]  }
    - { role: fx.diary, tags: [ fx, diary ] }

  tasks:
    - name: Make sure we have a wheel group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

#    - name: Download redis docker images
#      docker_image:
#        name: "{{ item }}"
#      with_items:
#        - redis

#    - name: signal-scan-redis container
#      docker_container:
#        name: signal-scan-redis
#        image: redis
#        volumes:
#          - "{{fx['datadir']}}/signal-scan-redis:/data"
#        state: started
#        command: "redis-server --appendonly yes"
