---

- name: Setup fx server
  hosts: all

  roles:
    - { role: fx.api.frontend }
    - { role: fx.datafeed }
    - { role: fx.api.backend }
    - { role: fx.sniper }

  tasks:
    - name: Make sure we have a wheel group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Download redis docker images
      docker_image:
        name: "{{ item }}"
      with_items:
        - redis

    - name: signal-scan-redis container
      docker_container:
        name: signal-scan-redis
        image: redis
        volumes:
          - "{{fx['datadir']}}/signal-scan-redis:/data"
        state: started
        command: "redis-server --appendonly yes"
