---

- name: Setup fx server
  hosts: all
  become: True

  roles:
    - { role: fx.api.frontend }
    - { role: fx.datafeed }
    - { role: fx.api.backend }
    - { role: fx.sniper }
    - { role: fx.dataaccounts }

  tasks:
    - name: Make sure we have a wheel group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Setup sysctl domainname
      sysctl:
        name: kernel.domainname
        value: "{{ domainname }}"
        state: present
