---

- name: Setup fx server
  hosts: all
  become: True

  roles:
    - { role: geerlingguy.docker }
    - { role: singleplatform-eng.users }
    - { role: willshersystems.sshd }
    - { role: holms.fqdn }
    - { role: geerlingguy.nginx }
    - { role: fx.api.frontend }
    - { role: fx.datafeed }

  tasks:
    - name: Make sure we have a wheel group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Download docker images
      docker_image:
        name: "{{ item }}"
      with_items:
        - fxtrader/finance-api-data
        - redis

    - name: Setup sysctl domainname
      sysctl:
        name: kernel.domainname
        value: "{{ domainname }}"
        state: present
