---

- name: Setup fx server
  hosts: all
  become: True

  roles:
    - { role: geerlingguy.docker }
    - { role: singleplatform-eng.users }
    - { role: willshersystems.sshd }
    - { role: holms.fqdn }
    - { role: geerlingguy.nginx }

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

  tasks:
    - name: Make sure we have a wheel group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Download docker images
      docker_image:
        name: "{{ item }}"
      with_items:
        - fxtrader/finance-hostedtrader
        - fxtrader/finance-api-data
        - redis
        - mysqludf/ta

    - name: Setup sysctl domainname
      sysctl:
        name: kernel.domainname
        value: "{{ domainname }}"
        state: present

    - name: Configure nginx
      template:
        src: templates/nginx/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify:
      - restart nginx

    - name: Configure nginx default vhost
      template:
        src: templates/nginx/conf.d/default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
      notify:
      - restart nginx

    - name: Configure nginx api.fxhistoricaldata.com vhost
      template:
        src: templates/nginx/conf.d/api.conf.j2
        dest: /etc/nginx/conf.d/api.conf
        owner: root
        group: root
        mode: 0644
      notify:
      - restart nginx
